/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import static com.mycompany.sistema.ImageHandler.setImageToLabel;
import static com.mycompany.sistema.GerenciadorDeImagens.moverERenomearImagem;
import static com.mycompany.sistema.extra.firebase.FirebaseStorageDownloader.downloadImagesFromFirebase;
import static com.mycompany.sistema.extra.firebase.FirebaseStorageUploader.uploadImagesToFirebase;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.Bandeira;
import com.mycompany.sistema.guarda.classe.convert.BandeiraCovert;
import com.mycompany.sistema.guarda.classe.Validacao;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 55329
 */
public class Bandeiras extends javax.swing.JInternalFrame {
    private List<Bandeira> bandeiras = new ArrayList();
    private Dados dado = new Banco();
    private String tip = "Bandeiras";
    /**
     * Creates new form Bandeiras
     */
    public void atualizar(){
        DefaultTableModel pessoa = (DefaultTableModel)tabela.getModel();
        
        for(Bandeira bandeira : bandeiras){
            Object[] dados = {bandeira.getNome(),bandeira.getTipo(),bandeira.getStatus()};
            pessoa.addRow(dados);
        }
    }
    public Bandeiras() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        bandeiras = BandeiraCovert.DadoToStrig(dado.ler(tip));
        atualizar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inserir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        tabelas = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        Status = new javax.swing.JComboBox<>();
        Tipo = new javax.swing.JLabel();
        Statu = new javax.swing.JLabel();
        Imagem = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Inserir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Inserir.setText("Inserir");
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Excluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        tipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Historico", "Estado", "Liceu" }));

        tabelas.setBorder(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabelas.setViewportView(tabela);

        Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perfeito", "Analizando", "Repadando", "Danificada" }));

        Tipo.setText("Tipo");

        Statu.setText("Status");

        Imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Imagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabelas)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Statu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Excluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Status, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                                    .addComponent(Inserir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Statu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        bandeiras.get(tabela.getSelectedRow()).setNome(Nome.getText());
        bandeiras.get(tabela.getSelectedRow()).setTipo((String) tipo.getSelectedItem());
        bandeiras.get(tabela.getSelectedRow()).setStatus((String) Status.getSelectedItem());
        
        if(tabela.getSelectedRow() != -1){
            tabela.setValueAt(Nome.getText(), tabela.getSelectedRow(), 0);
            tabela.setValueAt(tipo.getSelectedItem(), tabela.getSelectedRow(), 1);
            tabela.setValueAt(Status.getSelectedItem(), tabela.getSelectedRow(), 2);
        }
        firestore.guardarOuAtualizar(tip, bandeiras.get(tabela.getSelectedRow()).getNome(), BandeiraCovert.formatarListaParaString(bandeiras.get(tabela.getSelectedRow())));
    }//GEN-LAST:event_EditarActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        Object[] dados = {Nome.getText(),tipo.getSelectedItem(),Status.getSelectedItem()};
        Bandeira dato = new Bandeira(Nome.getText(),  (String)tipo.getSelectedItem(), (String)Status.getSelectedItem());
        modelo.addRow(dados);
        bandeiras.add(dato);
        firestore.guardarOuAtualizar(tip, dato.getNome(), BandeiraCovert.formatarListaParaString(dato));
        
    }//GEN-LAST:event_InserirActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(tabela.getSelectedRow() != -1){
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            firestore.eliminar(tip, bandeiras.get(tabela.getSelectedRow()).getNome());
            bandeiras.remove(tabela.getSelectedRow());
            modelo.removeRow(tabela.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if(tabela.getSelectedRow() != -1){
            Nome.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            tipo.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 1));
            Status.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 1));
            setImageToLabel(Imagem, tabela.getValueAt(tabela.getSelectedRow(), 0).toString()+".png");
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void ImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemMouseClicked
        File destino = new File("src/main/java/imagens/");

        // Verifique se o destino existe, caso contrário, crie-o
        if (!destino.exists()) {
            destino.mkdirs();
        }

        // Chama a função para mover e renomear a imagem
        moverERenomearImagem(destino, Nome.getText());
    }//GEN-LAST:event_ImagemMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Inserir;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel Statu;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelas;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
