/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import static com.mycompany.sistema.guarda.classe.date.DataOrde.ordenarDatas;
import static com.mycompany.sistema.guarda.classe.date.DataUtils.obterDiasDaSemana;
import static com.mycompany.sistema.extra.execel.ExcelGeneratos.criarArquivoExcelComTabela;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.Aluno;
import com.mycompany.sistema.guarda.classe.convert.AlunosCovert;
import com.mycompany.sistema.guarda.classe.Validacao;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import java.awt.HeadlessException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 55329
 */
public class Chamada extends javax.swing.JInternalFrame {
    List<String> dias = new ArrayList();
    
    List<Aluno> alunos = new ArrayList<>();
    List<Usuario> membros = new ArrayList<>();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    Dados dado = new Banco();
    /**
     * Creates new form Chamada
     */
    public void atualizar(){
        DefaultTableModel pessoa = (DefaultTableModel)Dias_add.getModel();
        for(String dia : dias){
            Object[] dados = {dia};
            pessoa.addRow(dados);
        }
    }
    public void limparColunas() {
        DefaultTableModel modelo = (DefaultTableModel)Dias_add.getModel();
        int rowCount = modelo.getRowCount();

        // Remove todas as linhas da tabela
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    public DayOfWeek DiadaSemana(String dia){
        switch (dia) {
            case "Domindo":
                return DayOfWeek.SUNDAY;
                
            case "Segunda":
                return DayOfWeek.MONDAY;
                
            case "Terças":
                return DayOfWeek.TUESDAY;
            
            case "Quarta":
                return DayOfWeek.WEDNESDAY;
            
            case "Quinta":
                return DayOfWeek.THURSDAY;
            
            case "Sexta":
                return DayOfWeek.FRIDAY;
            
            case "Sabado":
                return DayOfWeek.SATURDAY;   
        }
        return null;
    }
    public Chamada() {
        initComponents();
        alunos = AlunosCovert.DadoToStrig(dado.ler("Alunos"));
        atualizar();
    }
    public Chamada(List<Usuario> membros) {
        initComponents();
        alunos = AlunosCovert.DadoToStrig(dado.ler("Alunos"));
        this.membros = membros;
        Grupo.addItem("Guarda");
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Grupo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dia_semana = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        criar = new javax.swing.JButton();
        base = new javax.swing.JScrollPane();
        Dias_add = new javax.swing.JTable();
        excluir = new javax.swing.JButton();
        i = new javax.swing.JFormattedTextField();
        f = new javax.swing.JFormattedTextField();

        setClosable(true);

        jLabel1.setText("Data de Inicio:");

        jLabel2.setText("Data de Final:");

        Grupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adididas com Bandeira", "Adididas sem Bandeira", "Adididas Masculina", "Gala" }));

        jLabel3.setText("Grupo:");

        jLabel4.setText("Dia da Semana:");

        dia_semana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dia_semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domindo", "Segunda", "Terças", "Quarta", "Quinta", "Sexta", "Sabado", "Domingo" }));

        add.setText("Adininar Dias da Semana");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        criar.setText("Criar Chamada");
        criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarActionPerformed(evt);
            }
        });

        Dias_add.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dias"
            }
        ));
        base.setViewportView(Dias_add);

        excluir.setText("Excluir Dias");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        try {
            i.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            f.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(base, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dia_semana, 0, 194, Short.MAX_VALUE)
                    .addComponent(criar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(i)
                    .addComponent(f))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dia_semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        LocalDate inicio = LocalDate.parse(i.getText(), formatter);
        LocalDate fim = LocalDate.parse(f.getText(), formatter);
        System.out.println(inicio);
        List<String> domingosFormatados = obterDiasDaSemana(inicio, fim, DiadaSemana((String) dia_semana.getSelectedItem()));
        for (String domingosFormatado : domingosFormatados) {
            if (!dias.contains(domingosFormatado)) {
                dias.add(domingosFormatado);
            }
        }
        dias = ordenarDatas(dias);
        limparColunas();
        atualizar();
    }//GEN-LAST:event_addActionPerformed

    private void criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarActionPerformed
        List<String> nomes = new ArrayList<>();
        if(Grupo.getSelectedItem() == "Guarda"){
            for (Usuario membro : membros) {
                nomes.add(membro.getNome());
            }
        }else{
            for (Aluno aluno : alunos) {
                if(Grupo.getSelectedItem().equals(aluno.getGrupo())){
                    nomes.add(aluno.getNome());
                }
            }
        }
        String filePath = "src\\\\Chamadas\\\\chamada_"+Grupo.getSelectedItem()+".xlsx";
        criarArquivoExcelComTabela(filePath, nomes, dias);
        /*try {
            convertExcelToPDF("src\\\\main\\\\java\\\\com\\\\mycompany\\\\sistema\\\\guarda\\\\arquivo\\\\\\\\chamada execel\\\\chamada_"+Grupo.getSelectedItem()+".xlsx", "src\\\\main\\\\java\\\\com\\\\mycompany\\\\sistema\\\\guarda\\\\arquivo\\\\\\\\chamada pdf\\\\chamada_"+Grupo.getSelectedItem()+".pdf");
            System.out.println("Conversão concluída!");
        } catch (Exception e) {
            e.printStackTrace();
        }*/
        limparColunas();
    }//GEN-LAST:event_criarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        if(Dias_add.getSelectedRow() != -1){
            DefaultTableModel modelo = (DefaultTableModel) Dias_add.getModel();
            modelo.removeRow(Dias_add.getSelectedRow());
            dias.remove(Dias_add.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dias_add;
    private javax.swing.JComboBox<String> Grupo;
    private javax.swing.JButton add;
    private javax.swing.JScrollPane base;
    private javax.swing.JButton criar;
    private javax.swing.JComboBox<String> dia_semana;
    private javax.swing.JButton excluir;
    private javax.swing.JFormattedTextField f;
    private javax.swing.JFormattedTextField i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
