/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import com.mycompany.sistema.guarda.classe.Aluno;
import com.mycompany.sistema.guarda.classe.convert.AlunosCovert;
import static com.mycompany.sistema.guarda.view.Menu.Base;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 55329
 */
public class ListBusca extends javax.swing.JInternalFrame {
    private List<Aluno> alunos = new ArrayList<>();
    private Dados dado = new Banco();
    private String tipo = "Alunos";
    /**
     * Creates new form Bandeiras
     */
    
    /*public void up(){
        DefaultTableModel pessoa = (DefaultTableModel)tabela.getModel();
        
        try{
            CollectionReference col = Conexcion.db.collection("Alunos");
            ApiFuture<QuerySnapshot> query = col.get();

            for(DocumentSnapshot document: query.get().getDocuments()){
                Object[] dados = {document.getString("Nome:"),
                    document.getString("Tipo:"),
                    document.getString("Status:")};
                pessoa.addRow(dados);
            }
        
        }catch(InterruptedException | ExecutionException e){
            System.err.println("Error: "+e.getMessage());
        }
    }*/
    public ListBusca() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        alunos = AlunosCovert.DadoToStrig(dado.ler(tipo));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelas = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        Grupo1 = new javax.swing.JComboBox<>();
        Statu1 = new javax.swing.JLabel();
        Atualizar = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setEnabled(false);

        tabelas.setBorder(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Turma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabelas.setViewportView(tabela);

        Grupo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Grupo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha", "Tarde", "Noite" }));
        Grupo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grupo1ActionPerformed(evt);
            }
        });

        Statu1.setText("Turno");

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Statu1)
                .addGap(18, 18, 18)
                .addComponent(Grupo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Grupo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Atualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Statu1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        DefaultTableModel pessoa = (DefaultTableModel) tabela.getModel();

        // Limpa a tabela antes de adicionar novos valores
        pessoa.setRowCount(0);

        // Adiciona os novos valores na tabela
        for (Aluno aluno : alunos) {
            if (Grupo1.getSelectedItem().equals(aluno.getTurno())) {
                Object[] dados = {aluno.getNome(), aluno.getTurma()};
                pessoa.addRow(dados);
            }
        }
    }//GEN-LAST:event_AtualizarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
       
    }//GEN-LAST:event_tabelaMouseClicked

    private void Grupo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grupo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grupo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JComboBox<String> Grupo1;
    private javax.swing.JLabel Statu1;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelas;
    // End of variables declaration//GEN-END:variables
}
