/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.Validacao;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import com.mycompany.sistema.guarda.view.Menu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 55329
 */
public final class ListGuarda extends javax.swing.JInternalFrame {
    private List <Usuario> membros = new ArrayList();
    private Usuario user = new Usuario();
    private Dados dado = new Banco();
    private String tipo = "Guarda";
    /**
     * Creates new form Bandeiras
     */
    public ListGuarda(Usuario user) {
        initComponents();
        this.user = user;
        membros = UsuarioCovert.DadoToStrig(dado.ler(tipo));
        atualizar();
    }
    public void atualizar(){
        DefaultTableModel pessoa = (DefaultTableModel)Tabela.getModel();
        
        for(Usuario user : membros){
            Object[] dados = {user.getNome(),user.getNivel(),user.getPatente(),user.getDivi()};
            pessoa.addRow(dados);
        }
    }
    public ListGuarda(List <Usuario> membros) {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        Tabela.setRowSorter(new TableRowSorter(modelo));
        this.membros = membros;
        atualizar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perfil = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Hierarquia = new javax.swing.JButton();
        Hierarquia_Subir = new javax.swing.JButton();
        tabelas = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        Perfil.setText("Ver Perfil");
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Hierarquia.setText("Hierarquia-");
        Hierarquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HierarquiaActionPerformed(evt);
            }
        });

        Hierarquia_Subir.setText("Hierarquia+");
        Hierarquia_Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hierarquia_SubirActionPerformed(evt);
            }
        });

        tabelas.setBorder(null);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Nivel", "Patente", "Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelas.setViewportView(Tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hierarquia_Subir, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hierarquia, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabelas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Perfil)
                    .addComponent(Excluir)
                    .addComponent(Hierarquia)
                    .addComponent(Hierarquia_Subir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        Perfil perf = new Perfil(membros.get(Tabela.getSelectedRow()), Validacao.verificarConselho(user));
        Menu.Base.add(perf,true);
        perf.setVisible(true);
    }//GEN-LAST:event_PerfilActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(Tabela.getSelectedRow() != -1){
            DefaultTableModel pessoa = (DefaultTableModel)Tabela.getModel();
            firestore.eliminar(tipo,membros.get(Tabela.getSelectedRow()).getLogin());
            membros.remove(Tabela.getSelectedRow());
            pessoa.removeRow(Tabela.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void HierarquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HierarquiaActionPerformed
        int nivel;
        if(Tabela.getSelectedRow() != -1){
            nivel = membros.get(Tabela.getSelectedRow()).getNivel() - 1;
            membros.get(Tabela.getSelectedRow()).setNivel(nivel);
            membros.get(Tabela.getSelectedRow()).verificarpatente();
            
            Tabela.setValueAt(membros.get(Tabela.getSelectedRow()).getNivel(), Tabela.getSelectedRow(), 1);
            Tabela.setValueAt(membros.get(Tabela.getSelectedRow()).getPatente(), Tabela.getSelectedRow(), 2);
            firestore.guardarOuAtualizar(tipo, membros.get(Tabela.getSelectedRow()).getLogin(), UsuarioCovert.formatarListaParaString(membros.get(Tabela.getSelectedRow())));
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_HierarquiaActionPerformed

    private void Hierarquia_SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hierarquia_SubirActionPerformed
        int nivel;
        if(Tabela.getSelectedRow() != -1){
            nivel = membros.get(Tabela.getSelectedRow()).getNivel() + 1;
            membros.get(Tabela.getSelectedRow()).setNivel(nivel);
            membros.get(Tabela.getSelectedRow()).verificarpatente();
            
            Tabela.setValueAt(membros.get(Tabela.getSelectedRow()).getNivel(), Tabela.getSelectedRow(), 1);
            Tabela.setValueAt(membros.get(Tabela.getSelectedRow()).getPatente(), Tabela.getSelectedRow(), 2);
            firestore.guardarOuAtualizar(tipo, membros.get(Tabela.getSelectedRow()).getLogin(), UsuarioCovert.formatarListaParaString(membros.get(Tabela.getSelectedRow())));
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_Hierarquia_SubirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Hierarquia;
    private javax.swing.JButton Hierarquia_Subir;
    private javax.swing.JButton Perfil;
    private javax.swing.JTable Tabela;
    private javax.swing.JScrollPane tabelas;
    // End of variables declaration//GEN-END:variables
}
