/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.Aluno;
import com.mycompany.sistema.guarda.classe.convert.AlunosCovert;
import com.mycompany.sistema.guarda.classe.convert.BandeiraCovert;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import com.mycompany.sistema.guarda.view.Menu;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author 55329
 */
public final class ListRecrutamento extends javax.swing.JInternalFrame {
    private List<Usuario> membros = new ArrayList();
    private List<Aluno> alunos = new ArrayList();
    private List<Usuario> recrutas = new ArrayList();
    private List<Integer> ids = new ArrayList();
    private Dados dado = new Banco();
    private String tipo = "Guarda";
    /**
     * Creates new form Bandeiras
     */
    public ListRecrutamento() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        Tabela.setRowSorter(new TableRowSorter(modelo));
        membros = UsuarioCovert.DadoToStrig(dado.ler(tipo));
        for (int i = 0; i < membros.size()-1; i++) {
            if(membros.get(i).getNivel() == 0){
                ids.add(i);
                recrutas.add(membros.get(i));
            }
        }
        for (Aluno recruta : AlunosCovert.DadoToStrig(dado.ler("Alunos"))) {
            if("Recruta".equals(recruta.getGrupo()))
               recrutas.add(recruta); 
        }
        atualizar();
    }
    public void atualizar(){
        DefaultTableModel pessoa = (DefaultTableModel)Tabela.getModel();
        
        for(Usuario user : recrutas){
            Object[] dados = {user.getNome(),user.getTurma(),user.getTurno()};
            pessoa.addRow(dados);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perfil = new javax.swing.JButton();
        Reprovado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Aprovado = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        Perfil.setText("Criar Arquivo Com Dados dos Recrutas");
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Reprovado.setText("Reprovado");
        Reprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReprovadoActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Turma", "Turno"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        Aprovado.setText("Aprovado");
        Aprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprovadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)
                        .addComponent(Aprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Perfil)
                    .addComponent(Reprovado)
                    .addComponent(Aprovado))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        String caminhoArquivo = "src\\\\main\\\\java\\\\com\\\\mycompany\\\\sistema\\\\guarda\\\\arquivo\\\\Recrutas.xlsx";
        File arquivo = new File(caminhoArquivo);
        Workbook workbook;
        Sheet sheet;

        if (arquivo.exists()) {
            try (FileInputStream fis = new FileInputStream(arquivo)) {
                workbook = new XSSFWorkbook(fis);
                sheet = workbook.getSheetAt(0);
            } catch (IOException e) {
                e.printStackTrace();
                return;
            }
        } else {
            workbook = new XSSFWorkbook();
            sheet = workbook.createSheet("Alunos");

            // Criar cabeçalhos
            Row headerRow = sheet.createRow(0);
            headerRow.createCell(0).setCellValue("Nome");
            headerRow.createCell(1).setCellValue("Turma");
            headerRow.createCell(2).setCellValue("Turno");
        }

        int rowNum = sheet.getLastRowNum() + 1;

        for (Usuario aluno : recrutas) {
            Row row = sheet.createRow(rowNum++);
            row.createCell(0).setCellValue(aluno.getNome());
            row.createCell(1).setCellValue(aluno.getTurma());
            row.createCell(2).setCellValue(aluno.getTurno());
        }

        try (FileOutputStream fos = new FileOutputStream(caminhoArquivo)) {
            workbook.write(fos);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                workbook.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_PerfilActionPerformed

    private void ReprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReprovadoActionPerformed
        if(Tabela.getSelectedRow() != -1){
            firestore.eliminar(tipo, recrutas.get(Tabela.getSelectedRow()).getNome());
            recrutas.remove(Tabela.getSelectedRow());
            ids.remove(Tabela.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_ReprovadoActionPerformed

    private void AprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprovadoActionPerformed
        if(Tabela.getSelectedRow() != -1){
            //recrutas.get(Tabela.getSelectedRow()).setNivel(1);
            recrutas.get(Tabela.getSelectedRow()).setLogin(recrutas.get(Tabela.getSelectedRow()).getNome());
            recrutas.get(Tabela.getSelectedRow()).setSenha("123");
            recrutas.get(Tabela.getSelectedRow()).verificarDivisao();
            firestore.guardarOuAtualizar(tipo, recrutas.get(Tabela.getSelectedRow()).getNome(), UsuarioCovert.formatarListaParaString(recrutas.get(Tabela.getSelectedRow())));
            firestore.eliminar("Alunos", recrutas.get(Tabela.getSelectedRow()).getNome());
            recrutas.remove(Tabela.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_AprovadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aprovado;
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Reprovado;
    private javax.swing.JTable Tabela;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
