/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.Aluno;
import com.mycompany.sistema.guarda.classe.convert.AlunosCovert;
import com.mycompany.sistema.guarda.classe.Validacao;
import static com.mycompany.sistema.guarda.view.Menu.Base;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 55329
 */
public class ListPelotoes extends javax.swing.JInternalFrame {
    private List<Aluno> alunos = new ArrayList<>();
    private Dados dado = new Banco();
    private String tipo = "Alunos";
    /**
     * Creates new form Bandeiras
     */
    public void atualizar(){
        DefaultTableModel pessoa = (DefaultTableModel)tabela.getModel();
        
        for(Aluno aluno : alunos){
            Object[] dados = {aluno.getNome(),aluno.getGrupo(),aluno.getTurma(),aluno.getTurno()};
            pessoa.addRow(dados);
        }
    }
    
    
    
    /*public void up(){
        DefaultTableModel pessoa = (DefaultTableModel)tabela.getModel();
        
        try{
            CollectionReference col = Conexcion.db.collection("Alunos");
            ApiFuture<QuerySnapshot> query = col.get();

            for(DocumentSnapshot document: query.get().getDocuments()){
                Object[] dados = {document.getString("Nome:"),
                    document.getString("Tipo:"),
                    document.getString("Status:")};
                pessoa.addRow(dados);
            }
        
        }catch(InterruptedException | ExecutionException e){
            System.err.println("Error: "+e.getMessage());
        }
    }*/
    public ListPelotoes() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        alunos = AlunosCovert.DadoToStrig(dado.ler(tipo));
        atualizar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inserir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        tabelas = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        Grupo = new javax.swing.JComboBox<>();
        Tipo = new javax.swing.JLabel();
        Statu = new javax.swing.JLabel();
        Turma = new javax.swing.JTextField();
        Turno = new javax.swing.JComboBox<>();
        Statu1 = new javax.swing.JLabel();
        Recomendar = new javax.swing.JButton();
        Chamada = new javax.swing.JButton();
        Telefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        Inserir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Inserir.setText("Inserir");
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Excluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Telefone");

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        tabelas.setBorder(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Grupo", "Turma", "Turno", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabelas.setViewportView(tabela);

        Grupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adididas com Bandeira", "Adididas sem Bandeira", "Adididas Masculina", "Gala", "Recrutas da Guarda" }));

        Tipo.setText("Turma");

        Statu.setText("Grupo");

        Turma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurmaActionPerformed(evt);
            }
        });

        Turno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha", "Tarde", "Noite" }));

        Statu1.setText("Turno");

        Recomendar.setText("Recomendar para Guarda");
        Recomendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendarActionPerformed(evt);
            }
        });

        Chamada.setText("Criar Chamada");
        Chamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamadaActionPerformed(evt);
            }
        });

        Telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefone)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tipo)
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Turma, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Statu)
                            .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Statu1)
                            .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inserir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Recomendar, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Chamada, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Tipo)
                            .addComponent(Statu)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inserir)
                            .addComponent(Editar)
                            .addComponent(Excluir)
                            .addComponent(Turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Statu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recomendar)
                    .addComponent(Chamada))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(tabela.getSelectedRow() != -1){
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            firestore.eliminar(tipo, alunos.get(tabela.getSelectedRow()).getNome());
            alunos.remove(tabela.getSelectedRow());
            modelo.removeRow(tabela.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        
        if(tabela.getSelectedRow() != -1){
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            alunos.get(tabela.getSelectedRow()).setNome(Nome.getText());
            alunos.get(tabela.getSelectedRow()).setTurma(Turma.getText());
            alunos.get(tabela.getSelectedRow()).setGrupo((String) Grupo.getSelectedItem());
            alunos.get(tabela.getSelectedRow()).setTurno((String) Turno.getSelectedItem());
            alunos.get(tabela.getSelectedRow()).setTelefone((String) Telefone.getText());
        }
        tabela.setValueAt(Nome.getText(), tabela.getSelectedRow(), 0);
        tabela.setValueAt(Turma.getText(), tabela.getSelectedRow(), 2);
        tabela.setValueAt(Turno.getSelectedItem(), tabela.getSelectedRow(), 3);
        tabela.setValueAt(Telefone.getText(), tabela.getSelectedRow(), 4);
        tabela.setValueAt(Grupo.getSelectedItem(), tabela.getSelectedRow(), 1);
        firestore.guardarOuAtualizar(tipo, alunos.get(tabela.getSelectedRow()).getNome(), AlunosCovert.formatarListaParaString(alunos.get(tabela.getSelectedRow())));
    }//GEN-LAST:event_EditarActionPerformed

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed

        Aluno als = new Aluno();
        als.setNome(Nome.getText());
        als.setGrupo((String)Grupo.getSelectedItem());
        als.setTurma(Turma.getText());
        als.setTelefone(Telefone.getText());
        als.setTurno((String)Turno.getSelectedItem());
        alunos.add(als);
        firestore.guardarOuAtualizar(tipo, als.getNome(), AlunosCovert.formatarListaParaString(als));

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        Object[] dados = {Nome.getText(),Grupo.getSelectedItem(),Turma.getText(),Turno.getSelectedItem(),Telefone.getText()};
        modelo.addRow(dados);
    }//GEN-LAST:event_InserirActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TurmaActionPerformed

    private void ChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamadaActionPerformed
        Chamada dados = new Chamada();
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_ChamadaActionPerformed

    private void RecomendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendarActionPerformed
        alunos.get(tabela.getSelectedRow()).setDivi(alunos.get(tabela.getSelectedRow()).getGrupo());
        alunos.get(tabela.getSelectedRow()).setGrupo("Recruta");
        firestore.guardarOuAtualizar(tipo, alunos.get(tabela.getSelectedRow()).getNome(), AlunosCovert.formatarListaParaString(alunos.get(tabela.getSelectedRow())));
        tabela.setValueAt("Recruta", tabela.getSelectedRow(), 1);
    }//GEN-LAST:event_RecomendarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if(tabela.getSelectedRow() != -1){
            Nome.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            Turma.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chamada;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JComboBox<String> Grupo;
    private javax.swing.JButton Inserir;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton Recomendar;
    private javax.swing.JLabel Statu;
    private javax.swing.JLabel Statu1;
    private javax.swing.JTextField Telefone;
    private javax.swing.JLabel Tipo;
    private javax.swing.JTextField Turma;
    private javax.swing.JComboBox<String> Turno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelas;
    // End of variables declaration//GEN-END:variables
}
