/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import static com.mycompany.sistema.extra.execel.ExcelGeneratos.exportarTabelaParaExcel;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.Aluno;
import com.mycompany.sistema.guarda.classe.Medalha;
import com.mycompany.sistema.guarda.classe.convert.AlunosCovert;
import com.mycompany.sistema.guarda.classe.Validacao;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import static com.mycompany.sistema.guarda.view.Menu.Base;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 55329
 */
public class ListUniformes extends javax.swing.JInternalFrame {
    private List<Usuario> membros = new ArrayList<>();
    private Dados dado = new Banco();
    private String tipo = "Guarda";
    /**
     * Creates new form Bandeiras
     */
    public void Salvar(int id) {
            Map<String, Object> peças = new HashMap<>();
            peças.put("Dalmo", tabela.getValueAt(id, 1).toString());
            peças.put("Calca", tabela.getValueAt(id, 2).toString());
            peças.put("Patente", tabela.getValueAt(id, 3).toString());
            peças.put("Cordel", tabela.getValueAt(id, 4).toString());
            peças.put("Facha", tabela.getValueAt(id, 5).toString());
            
            try{
                firestore.guardarOuAtualizar("Uniforme",tabela.getValueAt(id, 0).toString(), peças);
            }catch (HeadlessException e){
                System.err.println("Error: "+e.getMessage());
                //JOptionPane.showMessageDialog(null, "Error al guar");
            }
        
    }
    public void Atualizar() {
        
        for (int i = 0; i < membros.size(); i++) {
            List<String> dados = new ArrayList<>();
            try{
                List<String>campos = new ArrayList<>();
                campos.add("Dalmo");
                campos.add("Calca");
                campos.add("Patente");
                campos.add("Cordel");
                campos.add("Facha");
                dados = firestore.lerDados("Uniforme", tabela.getValueAt(i, 0).toString(), dados);
                Object[] dado = {tabela.getValueAt(i, 0).toString(),dados.get(0),dados.get(1),dados.get(2),dados.get(3),dados.get(4),dados.get(5)};
            }catch (Exception e) {
                System.out.println("Erro ao ler dados: " + e.getMessage());
            }
        }
    }
    
    /*public void up(){
        DefaultTableModel pessoa = (DefaultTableModel)tabela.getModel();
        
        try{
            CollectionReference col = Conexcion.db.collection("Alunos");
            ApiFuture<QuerySnapshot> query = col.get();

            for(DocumentSnapshot document: query.get().getDocuments()){
                Object[] dados = {document.getString("Nome:"),
                    document.getString("Tipo:"),
                    document.getString("Status:")};
                pessoa.addRow(dados);
            }
        
        }catch(InterruptedException | ExecutionException e){
            System.err.println("Error: "+e.getMessage());
        }
    }*/
    public ListUniformes() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        membros = UsuarioCovert.DadoToStrig(dado.ler(tipo));
        
        DefaultTableModel pessoa = (DefaultTableModel)tabela.getModel();
        
        for(Usuario user : membros){
            Object[] dados = {user.getNome(),"Perfeito","Perfeito","Perfeito","Perfeito","Perfeito"};
            pessoa.addRow(dados);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Editar = new javax.swing.JButton();
        tabelas = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        Statu = new javax.swing.JLabel();
        Peça = new javax.swing.JComboBox<>();
        Status = new javax.swing.JComboBox<>();
        Peca = new javax.swing.JLabel();
        Criar_pLanilha = new javax.swing.JButton();
        Tnome = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        Editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        tabelas.setBorder(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dalmo", "Calca", "Patente", "Cordel", "Facha"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabelas.setViewportView(tabela);

        Statu.setText("Status:");

        Peça.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Peça.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dalmo", "Calca", "Patente", "Cordel", "Facha" }));

        Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perfeito", "Trocar", "Danificado", "Ausente" }));

        Peca.setText("Peça:");

        Criar_pLanilha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Criar_pLanilha.setText("Criar Planilha");
        Criar_pLanilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criar_pLanilhaActionPerformed(evt);
            }
        });

        Tnome.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tnome)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Nome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Peça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Peca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Criar_pLanilha))
                            .addComponent(Statu))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tnome)
                            .addComponent(Peca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Peça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nome)
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Statu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Editar)
                            .addComponent(Criar_pLanilha))))
                .addComponent(tabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        
        if(tabela.getSelectedRow() != -1){
            switch ((String) Peça.getSelectedItem()) {
                case "Dalmo" -> {
                    tabela.setValueAt((String) Status.getSelectedItem(), tabela.getSelectedRow(), 1);
                }
                case "Calca" -> {
                    tabela.setValueAt((String) Status.getSelectedItem(), tabela.getSelectedRow(), 2);
                }
                case "Patente" -> {
                    tabela.setValueAt((String) Status.getSelectedItem(), tabela.getSelectedRow(), 3);
                }
                case "Cordel" -> {
                    tabela.setValueAt((String) Status.getSelectedItem(), tabela.getSelectedRow(), 4);
                }
                case "Facha" -> {
                    tabela.setValueAt((String) Status.getSelectedItem(), tabela.getSelectedRow(), 5);
                }
            }
            Salvar(tabela.getSelectedRow());
        }
        //tabela.setValueAt(Nome.getText(), tabela.getSelectedRow(), 0);
        
    }//GEN-LAST:event_EditarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if(tabela.getSelectedRow() != -1){
            Nome.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void Criar_pLanilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criar_pLanilhaActionPerformed
        String filePath = "src\\\\Uniformes.xlsx";
        exportarTabelaParaExcel(tabela, filePath);
    }//GEN-LAST:event_Criar_pLanilhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Criar_pLanilha;
    private javax.swing.JButton Editar;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel Peca;
    private javax.swing.JComboBox<String> Peça;
    private javax.swing.JLabel Statu;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JLabel Tnome;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelas;
    // End of variables declaration//GEN-END:variables
}
