/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.menu.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Dados;
import com.mycompany.sistema.guarda.classe.convert.BandeiraCovert;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55329
 */
public class Recrutamento extends javax.swing.JInternalFrame {
    private List<Usuario> membros = new ArrayList();
    private List<Usuario> recrutas = new ArrayList();
    private List<Integer> ids = new ArrayList();
    private Dados dado = new Arquivo();
    private String tipo = "Guarda";
    /**
     * Creates new form Recrutamento
     */
    public Recrutamento() {
        initComponents();
        membros = UsuarioCovert.DadoToStrig(dado.ler(tipo));
        for (int i = 0; i < membros.size()-1; i++) {
            if(membros.get(i).getNivel() == 0){
                ids.add(i);
                recrutas.add(membros.get(i));
            }
        }
        atualizar();
    }
    public void atualizar(){
        DefaultTableModel pessoa = (DefaultTableModel)Tablem.getModel();
        
        for(Usuario user : recrutas){
            Object[] dados = {user.getNome()};
            pessoa.addRow(dados);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        Tablem = new javax.swing.JTable();
        Reprovado = new javax.swing.JButton();
        Aprovado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        Tablem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));
        panel.setViewportView(Tablem);

        Reprovado.setText("Reprovado");
        Reprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReprovadoActionPerformed(evt);
            }
        });

        Aprovado.setText("Aprovado");
        Aprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprovadoActionPerformed(evt);
            }
        });

        jButton1.setText("Criar Lista de Recruta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(Aprovado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reprovado)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reprovado)
                    .addComponent(Aprovado)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReprovadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReprovadoActionPerformed

    private void AprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprovadoActionPerformed
        if(Tablem.getSelectedRow() != -1){
            recrutas.get(Tablem.getSelectedRow()).setNivel(1);
            membros.set(ids.get(Tablem.getSelectedRow()), recrutas.get(Tablem.getSelectedRow()));
            recrutas.remove(Tablem.getSelectedRow());
            ids.remove(Tablem.getSelectedRow());
        }else{
            System.out.println("Nada Selecinado!");
        }
    }//GEN-LAST:event_AprovadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aprovado;
    private javax.swing.JButton Reprovado;
    private javax.swing.JTable Tablem;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane panel;
    // End of variables declaration//GEN-END:variables
}
