/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import com.mycompany.beta.Medalha_Dado;
import static com.mycompany.sistema.extra.firebase.FirebaseStorageUploader.uploadImagesToFirebase;
import com.mycompany.sistema.guarda.classe.Aluno;
import com.mycompany.sistema.guarda.classe.convert.AlunosCovert;
import com.mycompany.sistema.guarda.classe.convert.BandeiraCovert;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import com.mycompany.sistema.guarda.classe.Bandeira;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import com.mycompany.sistema.guarda.classe.Validacao;
import com.mycompany.sistema.guarda.menu.view.Bandeiras;
import com.mycompany.sistema.guarda.menu.view.Chamada;
import com.mycompany.sistema.guarda.menu.view.Informacoes_pessoas;
import com.mycompany.sistema.guarda.menu.view.ListBusca;
import com.mycompany.sistema.guarda.menu.view.ListGuarda;
import com.mycompany.sistema.guarda.menu.view.ListPelotoes;
import com.mycompany.sistema.guarda.menu.view.ListRecrutamento;
import com.mycompany.sistema.guarda.menu.view.ListUniformes;
import com.mycompany.sistema.guarda.menu.view.Perfil;
import com.mycompany.sistema.guarda.menu.view.Recrutamento;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 55329
 */
public class Menu extends javax.swing.JFrame {
    private int id;
    private List<Usuario> membros = new ArrayList();
    private List<Aluno> alunos = new ArrayList();
    private List<Bandeira> bandeiras = new ArrayList();
    private Dados arq = new Arquivo();
    private String tipo = "Guarda";
    /**
     * Creates new form Menu
     */
    
    private void VN(Usuario user){
        boolean[] alt = user.alt();
        Menu.setVisible(alt[0]);
        Bandeira.setVisible(alt[1]);
        Pelotões.setVisible(alt[2]);
        Guarda.setVisible(alt[3]);
    }
    public Menu() {
        this.arq = new Banco();
        initComponents();
    }
    
    public Menu(List<Usuario> pessoa,int id) {
        this.arq = new Banco();
        
        initComponents();
        this.id = id;
        membros = pessoa;
        
        alunos = AlunosCovert.DadoToStrig(arq.ler("Aluno"));
        VN(membros.get(id));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Base = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        perfil = new javax.swing.JMenuItem();
        Bandeira = new javax.swing.JMenu();
        Bandeiras = new javax.swing.JMenuItem();
        Pelotões = new javax.swing.JMenu();
        List_todos_alunos = new javax.swing.JMenuItem();
        List_alunos_buscar = new javax.swing.JMenuItem();
        Chamada = new javax.swing.JMenuItem();
        Guarda = new javax.swing.JMenu();
        Lista_Java = new javax.swing.JMenuItem();
        Cadastro_guarda = new javax.swing.JMenuItem();
        List_todos_alunos1 = new javax.swing.JMenuItem();
        Chamada1 = new javax.swing.JMenuItem();
        Lista_Java1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Base.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jMenuBar1.setMinimumSize(new java.awt.Dimension(423, 50));

        Menu.setText("Meus dados");

        perfil.setText("perfil");
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        Menu.add(perfil);

        jMenuBar1.add(Menu);

        Bandeira.setText("Bandeira");

        Bandeiras.setText("Bandeiras");
        Bandeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandeirasActionPerformed(evt);
            }
        });
        Bandeira.add(Bandeiras);

        jMenuBar1.add(Bandeira);

        Pelotões.setText("Pelotões");

        List_todos_alunos.setText("Lista de Todos os Alunos");
        List_todos_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_todos_alunosActionPerformed(evt);
            }
        });
        Pelotões.add(List_todos_alunos);

        List_alunos_buscar.setText("Lista de Alunos a ser buscado");
        List_alunos_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_alunos_buscarActionPerformed(evt);
            }
        });
        Pelotões.add(List_alunos_buscar);

        Chamada.setText("Chamada");
        Chamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamadaActionPerformed(evt);
            }
        });
        Pelotões.add(Chamada);

        jMenuBar1.add(Pelotões);

        Guarda.setText("Menbros da guarda");

        Lista_Java.setText("Lista");
        Lista_Java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_JavaActionPerformed(evt);
            }
        });
        Guarda.add(Lista_Java);

        Cadastro_guarda.setText("Castrar");
        Cadastro_guarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_guardaActionPerformed(evt);
            }
        });
        Guarda.add(Cadastro_guarda);

        List_todos_alunos1.setText("Recrutamento");
        List_todos_alunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_todos_alunos1ActionPerformed(evt);
            }
        });
        Guarda.add(List_todos_alunos1);

        Chamada1.setText("Chamada");
        Chamada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chamada1ActionPerformed(evt);
            }
        });
        Guarda.add(Chamada1);

        Lista_Java1.setText("Uniforme");
        Lista_Java1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_Java1ActionPerformed(evt);
            }
        });
        Guarda.add(Lista_Java1);

        jMenuBar1.add(Guarda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        Perfil perf = new Perfil(membros.get(id));
        Base.add(perf);
        perf.setVisible(true);
    }//GEN-LAST:event_perfilActionPerformed

    private void Lista_JavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_JavaActionPerformed
        ListGuarda list = new ListGuarda(membros);
        Base.add(list);
        list.setVisible(true);
    }//GEN-LAST:event_Lista_JavaActionPerformed

    private void Cadastro_guardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_guardaActionPerformed
        
        Informacoes_pessoas dados = new Informacoes_pessoas();
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_Cadastro_guardaActionPerformed

    private void List_todos_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_todos_alunosActionPerformed
        ListPelotoes dados = new ListPelotoes();
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_List_todos_alunosActionPerformed

    private void BandeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandeirasActionPerformed
        Bandeiras dados = new Bandeiras();
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_BandeirasActionPerformed

    private void List_alunos_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_alunos_buscarActionPerformed
        ListBusca dados = new ListBusca();
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_List_alunos_buscarActionPerformed

    private void List_todos_alunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_todos_alunos1ActionPerformed
        ListRecrutamento fame = new ListRecrutamento();
        Base.add(fame);
        fame.setVisible(true);
    }//GEN-LAST:event_List_todos_alunos1ActionPerformed

    private void ChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamadaActionPerformed
        Chamada dados = new Chamada();
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_ChamadaActionPerformed

    private void Chamada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chamada1ActionPerformed
        Chamada dados = new Chamada(membros);
        Base.add(dados);
        dados.setVisible(true);
    }//GEN-LAST:event_Chamada1ActionPerformed

    private void Lista_Java1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_Java1ActionPerformed
        ListUniformes fame = new ListUniformes();
        Base.add(fame);
        fame.setVisible(true);
    }//GEN-LAST:event_Lista_Java1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            uploadImagesToFirebase();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Bandeira;
    public javax.swing.JMenuItem Bandeiras;
    public static javax.swing.JDesktopPane Base;
    public javax.swing.JMenuItem Cadastro_guarda;
    public javax.swing.JMenuItem Chamada;
    public javax.swing.JMenuItem Chamada1;
    public javax.swing.JMenu Guarda;
    public javax.swing.JMenuItem List_alunos_buscar;
    public javax.swing.JMenuItem List_todos_alunos;
    public javax.swing.JMenuItem List_todos_alunos1;
    public javax.swing.JMenuItem Lista_Java;
    public javax.swing.JMenuItem Lista_Java1;
    public javax.swing.JMenu Menu;
    public javax.swing.JMenu Pelotões;
    public javax.swing.JButton jButton1;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem perfil;
    // End of variables declaration//GEN-END:variables
}
