/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.guarda.view;

import com.mycompany.beta.Arquivo;
import com.mycompany.beta.Banco;
import com.mycompany.beta.Dados;
import com.mycompany.sistema.extra.firebase.firestore;
import com.mycompany.sistema.guarda.classe.perfil.Usuario;
import com.mycompany.sistema.guarda.classe.convert.UsuarioCovert;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 55329
 */
public class TelaInicial extends javax.swing.JFrame {
    private List<Usuario> membros = new ArrayList<>();
    private Dados dado = new Arquivo();
    private String tipo = "Guarda";
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        membros = UsuarioCovert.DadoToStrig(dado.ler(tipo));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        Senha = new javax.swing.JPasswordField();
        senha_visil = new javax.swing.JCheckBox();
        Casdastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema da Guarda"); // NOI18N
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Senha:");

        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeKeyPressed(evt);
            }
        });

        Entrar.setText("ENTRAR");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SenhaKeyPressed(evt);
            }
        });

        senha_visil.setText("Senha Visivel");
        senha_visil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_visilActionPerformed(evt);
            }
        });

        Casdastro.setText("Cadastrar");
        Casdastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasdastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(Senha)))
                    .addComponent(senha_visil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Casdastro, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(senha_visil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrar)
                    .addComponent(Casdastro))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        if(membros.isEmpty())
            JOptionPane.showMessageDialog(rootPane,"Não tem login Cadastrado!");
        String a;
        String b;
        int opc = 0;
        a = Nome.getText();
        b = Senha.getText();
        
        for (int i = 0; i < membros.size(); i++) {
            Usuario usere = membros.get(i);
            if(usere.getLogin().equals(a) && usere.getSenha().equals(b)){
                Menu frame = new Menu(membros,i);
                frame.setVisible(true);
                frame.setTitle("Nome:" + usere.getNome() + "      " + "Nivel de Acesso:" + usere.getNivel() + "      " + "Patente:" + usere.getPatente());
                frame.setExtendedState(frame.getExtendedState() | frame.MAXIMIZED_BOTH);
                i = membros.size()-1;
                dispose();
                opc = 0;
            }else if(usere.getLogin().equals(a) && !usere.getSenha().equals(b)){
                opc = 1;
            }else if(!usere.getLogin().equals(a) && usere.getSenha().equals(b)){
                opc = 2;
            }
            if(!usere.getLogin().equals(a) && !usere.getSenha().equals(b) && i == membros.size()-1){
                opc = 3;
            }
        }
        
        switch (opc) {
            case 1:
                JOptionPane.showMessageDialog(rootPane,"Senha incorreta!");
                break;
            case 2:
                JOptionPane.showMessageDialog(rootPane, "Login incorreta!");
                break;
            case 3:
                JOptionPane.showMessageDialog(rootPane,"Usuario não existe!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_EntrarActionPerformed

    private void senha_visilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_visilActionPerformed
        if(senha_visil.isSelected()){
            Senha.setEchoChar((char)0);
        }else{
            Senha.setEchoChar('*');
        }
    }//GEN-LAST:event_senha_visilActionPerformed

    private void CasdastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasdastroActionPerformed
        Usuario user = new Usuario();
        
        String codigo = JOptionPane.showInputDialog(null, "Codigo de Permição:", "Altorização", JOptionPane.PLAIN_MESSAGE);
        System.err.println(codigo);
        if(codigo.equals("1502")){
            String dado = JOptionPane.showInputDialog(null, "Digite seu login:", "Login", JOptionPane.PLAIN_MESSAGE); 
            user.setLogin(dado);
            dado = JOptionPane.showInputDialog(null, "Digite sua senha:", "Senha", JOptionPane.PLAIN_MESSAGE);
            user.setSenha(dado);
            user.setNivel(0);
            membros.add(user);
            //firestore.guardarOuAtualizar(tipo, user.getLogin(), UsuarioCovert.formatarListaParaString(user));
            UsuarioCovert.atualizar(user);
            Menu frame = new Menu(membros,membros.size()-1);
            frame.setVisible(true);
            frame.setTitle("Nome:" + user.getNome() + "      " + "Nivel de Acesso:" + user.getNivel() + "      " + "Patente:" + user.getPatente());
            frame.setExtendedState(frame.getExtendedState() | frame.MAXIMIZED_BOTH);
            dispose();
        }
    }//GEN-LAST:event_CasdastroActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            if(membros.isEmpty())
                JOptionPane.showMessageDialog(rootPane,"Não tem login Cadastrado!");
            String a;
            String b;
            int opc = 0;
            a = Nome.getText();
            b = Senha.getText();

            for (int i = 0; i < membros.size(); i++) {
                Usuario usere = membros.get(i);
                if(usere.getLogin().equals(a) && usere.getSenha().equals(b)){
                    Menu frame = new Menu(membros,i);
                    frame.setVisible(true);
                    frame.setTitle("Nome:" + usere.getNome() + "      " + "Nivel de Acesso:" + usere.getNivel() + "      " + "Patente:" + usere.getPatente());
                    frame.setExtendedState(frame.getExtendedState() | frame.MAXIMIZED_BOTH);
                    i = membros.size()-1;
                    dispose();
                    opc = 0;
                }else if(usere.getLogin().equals(a) && !usere.getSenha().equals(b)){
                    opc = 1;
                }else if(!usere.getLogin().equals(a) && usere.getSenha().equals(b)){
                    opc = 2;
                }
                if(!usere.getLogin().equals(a) && !usere.getSenha().equals(b) && i == membros.size()-1){
                    opc = 3;
                }
            }

            switch (opc) {
                case 1:
                    JOptionPane.showMessageDialog(rootPane,"Senha incorreta!");
                    break;
                case 2:
                    JOptionPane.showMessageDialog(rootPane, "Login incorreta!");
                    break;
                case 3:
                    JOptionPane.showMessageDialog(rootPane,"Usuario não existe!");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_SenhaKeyPressed

    private void NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            if(membros.isEmpty())
                JOptionPane.showMessageDialog(rootPane,"Não tem login Cadastrado!");
            String a;
            String b;
            int opc = 0;
            a = Nome.getText();
            b = Senha.getText();

            for (int i = 0; i < membros.size(); i++) {
                Usuario usere = membros.get(i);
                if(usere.getLogin().equals(a) && usere.getSenha().equals(b)){
                    Menu frame = new Menu(membros,i);
                    frame.setVisible(true);
                    frame.setTitle("Nome:" + usere.getNome() + "      " + "Nivel de Acesso:" + usere.getNivel() + "      " + "Patente:" + usere.getPatente());
                    frame.setExtendedState(frame.getExtendedState() | frame.MAXIMIZED_BOTH);
                    i = membros.size()-1;
                    dispose();
                    opc = 0;
                }else if(usere.getLogin().equals(a) && !usere.getSenha().equals(b)){
                    opc = 1;
                }else if(!usere.getLogin().equals(a) && usere.getSenha().equals(b)){
                    opc = 2;
                }
                if(!usere.getLogin().equals(a) && !usere.getSenha().equals(b) && i == membros.size()-1){
                    opc = 3;
                }
            }

            switch (opc) {
                case 1:
                    JOptionPane.showMessageDialog(rootPane,"Senha incorreta!");
                    break;
                case 2:
                    JOptionPane.showMessageDialog(rootPane, "Login incorreta!");
                    break;
                case 3:
                    JOptionPane.showMessageDialog(rootPane,"Usuario não existe!");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_NomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casdastro;
    private javax.swing.JButton Entrar;
    private javax.swing.JTextField Nome;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox senha_visil;
    // End of variables declaration//GEN-END:variables
}
